### ISSUE TITLE
Staking Deposit Adresse anzeigen

### ISSUE THREAD

**Issue by SwissBlueDragon** [LOCKbusiness/api#56]
Aktuell wird in der LOCK Ansicht die Deposit Adresse nicht dargestellt. 
Wo könnte man dies tun?
Design Vorschläge?

**Comment by LOCKstaking** [comment]
Ich wuerde hier einfach das GSheet verlinken, z.B. : "Deine Staking Balance anzeigen"

**Comment by LOCKstaking** [comment]
Resolved!
